### ISSUE TITLE
Kanban-Setup

### ISSUE THREAD

**Issue by AnsarIbrahim** [marvin-nyalik/RecipeApp#11]
In this Project three Members:

[Link of Project](https://github.com/marvin-nyalik/RecipeApp/projects/1)
@marvin-nyalik , @Zafron047 , @AnsarIbrahim

**Comment by AbelG101** [comment]
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzFmY2U0ZTkwMmM3ZTM5MDBkNjhhZjk0MjI0OTU3MGNjYjMyMmRhOCZjdD1n/M1fddM48g9084bJMEX/giphy.gif)


# Hi @AnsarIbrahim, @marvin-nyalik & @Zafron047 👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Proper kanban template is used ✔
- Each card is assigned a team member ✔
- Tasks are distributed fairly ✔

## Required Changes ♻️
- Excellent progress so far, everyone! I've noticed that we're almost there, but we missed a few requirements. To ensure completeness, let's address them by adding separate task cards for each of the following requirements:
    - [ ] Make sure there are no N+1 queries happening.
    - [ ] Write unit and integration tests
    - [ ] Recipe details: Should have a modal to choose an inventory to create a shopping list with, as in the wireframe.
    - [ ] Follow the layout of the wireframes provided. Personalize the rest of the design including colors, typographies, spacings, etc.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by thecodechaser** [comment]
## STATUS: APPROVED 🟢

## Hi @marvin-nyalik, and Team👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
